name: ssjc_p
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.0.0
  http: ^1.6.0
  get_storage: ^2.1.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4   

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ssjc.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/ssjc.jpg
    - assets/saraswati1.jpg
    - assets/ssjc.jpg
    - assets/girl.jpg
    - assets/QRcode.svg
